### ISSUE TITLE
Decorations don't work

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#107]
The recipe seems to be producing blocks decorated with air.

**Comment by da3dsoul** [comment]
Haha interesting, so it becomes invisible? Or they just don't work...that's much less fun.

**Comment by planetguy32** [comment]
They show the purple and black default icon instead of the camouflage block's texture. It might be two separate bugs, but dumping all the fields with a debug item indicates that the camouflage block is air in the tile entity - I'd have to check NBT for the item.

**Comment by da3dsoul** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286750-in-game-nbtedit-edit-mob-spawners-attributes-in
I strongly recommend for debugging.

**Comment by planetguy32** [comment]
I tried it, but the latest build linked is for 1.7.2 and it crashes when I try to use it on Minecraft 1.7.10.

**Comment by da3dsoul** [comment]
No, hang on there is an update.

**Comment by da3dsoul** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286750-in-game-nbtedit-edit-mob-spawners-attributes-in?page=77

**Comment by planetguy32** [comment]
Thanks, it worked nicely. The problem is in copying NBT data from the item to the block.
