### ISSUE TITLE
Make a packet that tells clients what the "velocity" of carriages is.

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#109]

**Comment by planetguy32** [comment]
Does adding it to WriteCommonRecord() and ReadCommonRecord() do what you need? The NBT tags written here are synchronized to the client.

**Comment by da3dsoul** [comment]
Maybe...

**Comment by da3dsoul** [comment]
RIGHT! I remember why I didn't just do this: the velocity is controlled in the config, and it never changes at runtime. Using extra data in every block in packets is just wasteful. A packet on login would be far better (and allows for ease of handling players that weren't in the world from the start).

**Comment by planetguy32** [comment]
NBT tags don't necessarily need to exist, so we could let spectres include their own velocity in a tag to override the client's config and default to the client's config. Checking if a NBT tag exists is pretty cheap, IIRC - they use HashMaps as their underlying storage so it should be a simple operation.

**Comment by da3dsoul** [comment]
Made a packet, need to test it over network.

**Comment by da3dsoul** [comment]
It works, as of now, it doesn't change the value back to config (local) until restart of minecraft.

**Comment by da3dsoul** [comment]
It works enough, I'm not going to hold this up for release.
