### ISSUE TITLE
Rewrite TileEntityMotiveSpectre to not send as enormous packets.

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#110]
I'll take this one, optimizing and network is kind of my thing.

**Comment by da3dsoul** [comment]
beastgir teleported his island and kicked everyone and then we couldn't log back in until he broke the carriage.

**Comment by da3dsoul** [comment]
MotiveSpectres didn't appear to be the issue (although I optimized them a teensy bit), Template Carriages (and Memory Carriages) sent a huge packet that didn't need to send.

**Comment by planetguy32** [comment]
WriteCommonRecord() is saved both locally and synchronized to the client. WriteClientRecord() is only synchronized, and WriteServerRecord() is only saved locally on the server.
