### ISSUE TITLE
Placing FMP carriages hangs the client

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#114]
It doesn't look like the code path involves any of our methods. Are we using FMP wrong?

**Comment by da3dsoul** [comment]
Those are your baby. I don't even know what they are supposed to do. Regardless, the post on the forums is right: It has been a long time since a release, we should wrap it up into a stable build. I've been playing with the current codeset and it works nicely.

**Comment by da3dsoul** [comment]
Well, except for these...but I don't use them.

**Comment by planetguy32** [comment]
Further research indicates that https://github.com/planetguy32/RemainInMotion/commit/132b96e82e9b51ceb7940d38c5222cda8e583b90 broke it, and that git bisect is awesome for finding regressions.
