### ISSUE TITLE
Better per-mod special case handling

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#120]
It seems like we're winding up with special cases for more and more mods (FMP, Buildcraft and ChickenChunks come to mind). I have a few more for rotation that I'd like to implement (EnderIO and probably most of the hundreds of mods out there need them, and FMP and BC could use rotation handlers for their multi-part blocks) but even just the hooks already implemented are starting to affect the code's readability.

**Comment by da3dsoul** [comment]
I created #106 to list mod that need special handling (with block names please). Buildcraft already has rotation special casing for some things (namely quarry and filler, gates need it)

**Comment by planetguy32** [comment]
EnderIO, Buildcraft facades and FMP microblocks all now have handlers.

**Comment by planetguy32** [comment]
We've split out the hooks into the event bus, so this issue isn't much use anymore.
