### ISSUE TITLE
Crash when breaking a redstone block slightly above a set of fmp carriages which are in motion

### ISSUE THREAD

**Issue by BBoldt** [planetguy32/RemainInMotion#121]
* Planetguylib 1.5
* Remain in Motion 2.5.2
* forge multipart 320

Crashlog:
http://hastebin.com/xojanafuzo.hs

I got a screenshot as it was crashing, if it helps: 
![](http://i.imgur.com/YpWfDP3.jpg)

**Comment by da3dsoul** [comment]
Do me a favor and do the exact same thing, except leave out the redstone block and just break the specter. Post the results.
I don't know how to use those, but I can program.

**Comment by da3dsoul** [comment]
I can't reproduce this.

**Comment by BBoldt** [comment]
Sorry, kinda forgot about this, it was kind of a weird circumstance.

I don't know how to do it without the redstone block as the redstone block was the thing triggering the engine and moving it. If I remember correctly, I broke both the redstone block and what was behind it at the same time, resulting in the game freezing on that image and then crashing.

**Comment by da3dsoul** [comment]
Ah that was an nei/waila/multipart error then. The log points to it at least
