### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#122]
public TileEntityFrameCarriage() {
        RiMRegistry.registerCloseableFactory(new ICloseableFactory() {
            @Override
            public ICloseable retrieve(TileEntity te) {
                return (ICloseable) te;
            }

            @Override
            public Class validClass() {
                return TileEntityFrameCarriage.class;
            }
        });
    }

This is defined in the wrong place.

**Comment by da3dsoul** [comment]
It usually happens if there is lag and a large amount of Frame Carriages moving.

**Comment by planetguy32** [comment]
Oops! Good catch. It was probably intended to go in the block constructor (which is only called once) - not that that's necessarily the most sensible place for it.
