### ISSUE TITLE
Place directed carriages like pistons

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#124]
It makes sense and is more consistent with vanilla Minecraft.

**Comment by da3dsoul** [comment]
Already fixed this one, too.

**Comment by planetguy32** [comment]
Is it up in the repo?

**Comment by da3dsoul** [comment]
Yep, it has been for awhile. I just forgot to close this when it was
relevant.

**Comment by planetguy32** [comment]
Great.

**Comment by da3dsoul** [comment]
Found it, the commit was renamed due to conflicts. https://github.com/planetguy32/RemainInMotion/commit/37d7dfd5b97d9605358695c93a391fb43853f1b3
