### ISSUE TITLE
Recursion causing world to crash on load

### ISSUE THREAD

**Issue by TheLoneWolfling** [planetguy32/RemainInMotion#126]
Happened when I clicked on a hollow carriage with a normal carriage.

My guess is that it's trying to look up itself to see what texture it should use to camouflage itself?

Relevant line is

    java.lang.StackOverflowError: Unexpected error
    [...]
    at me.planetguy.remaininmotion.base.BlockCamouflageable.func_149720_d(BlockCamouflageable.java:81)
    [...]

http://paste.ee/p/yL7Dx

**Comment by TheLoneWolfling** [comment]
Also, it says 2.5.2, but I've got RemainInMotion-2.5.3.jar installed. I'm a little confused about that.

**Comment by da3dsoul** [comment]
Ah, thanks. I see what caused it.

**Comment by TheLoneWolfling** [comment]
I fixed it for now by disabling experimentalColor in the config, for anyone else having this problem. Also: may I suggest you wrap all "non-essential" methods in try/catch blocks that (configurably) log the error but don't hard-crash? It's better (generally) to have, say, a block return the wrong light value than crashing every load. At least the first is playable.
