### ISSUE TITLE
TileEntities are not cleaning up after themselves

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#130]
I think I may have fixed it but can't test right now.

**Comment by da3dsoul** [comment]
The blocks are all cleaned up, so I suspect there is a problem in the way that the sneaky world util removes them.

**Comment by da3dsoul** [comment]
This is puzzling. I'm about ready for bed. I'll check to see if my latest attempt works and if not, oh well.

**Comment by da3dsoul** [comment]
Mk, no. G'night...or day.

**Comment by planetguy32** [comment]
It does seem that we don't do any sort of cleanup of TileEntities that get overwritten, but if any are left behind I don't think they get persisted (at least, I've checked the region file of a test area and haven't seen phantom TEs). Did the problem build take a wide path across a chunk-loaded area?

**Comment by da3dsoul** [comment]
I discovered it with this: http://i58.tinypic.com/6r1o29.png They are removed at world close/ chunk save. The issue lies in that a chunk destroyer makes 512 new tiles on each movement, not including frames or extras like the tesseract or chests. They run for a night without cleaning up, and you have 50k specter entities taking 11GB of RAM. I thank the world (my full-time job) that I have 28GB of RAM and gave Minecraft 12 of it (with some args to tell java to clean up it's shit, even if it does have plenty of room)

**Comment by da3dsoul** [comment]
I recommend OPIS, as it told me it was RiM's fault. beastgir chewed me out for that one. 
"DICK! It's your fault!" 
"Umm, what?"
"Remain in Motion"
"I'm not the only one who works on it."
"But I'm not going to scream 'dick' at planetguy. He seems cool"
"Mk, fair enough"

**Comment by da3dsoul** [comment]
PS don't sort by mod with OPIS. It crashes.

**Comment by da3dsoul** [comment]
Ooo, just looked at it. We can't remove the check for empty list. Anything that doesn't move will have an empty list.

**Comment by da3dsoul** [comment]
I'm remarkably certain I tried that. We'll see.

**Comment by planetguy32** [comment]
There was something iterating over spectersToDestroy clearing TileEntities there, but those aren't the main body. 

Doesn't giving a foreach loop an empty list just not run anyway?

**Comment by da3dsoul** [comment]
No idea. https://docs.oracle.com/javase/8/docs/technotes/guides/language/foreach.html says nothing about it doing so.

**Comment by da3dsoul** [comment]
Okay, now we have chunk.removeTileEntity called in 2 places in SneakyWorldUtil::SetBlock. Once with ChunkX, Y, ChunkZ, and once with X,Y,Z. Which is correct? One with throw an error, do nothing, or remove the wrong tile.

**Comment by da3dsoul** [comment]
see https://github.com/planetguy32/RemainInMotion/commit/260c83acc6c1249701148d8c4fc72b503af93a01

**Comment by planetguy32** [comment]
It takes chunk coords. We remove TEs from the chunk, but I don't think we ever take them out of the world's list of active TEs.

**Comment by da3dsoul** [comment]
Indeed. Although that is private. Everything in the TileEntities is called while iterating through loadedTileEntities. If we try to remove from that, it will throw a ConcurrentModificationException. The to-be-removed list is field_147483_b. nvm I found it. func_147457_a(TileEntity entity)

**Comment by da3dsoul** [comment]
Cool, this has been bugging me for a few days. keke

**Comment by da3dsoul** [comment]
I'm currently moving a continent to make sure. Okay, it's like 8500 blocks, but still big.

**Comment by da3dsoul** [comment]
Mk, according to Opis, it is ~23000 blocks. And not cleaning up. My RAM says otherwise, I'll keep watching.

**Comment by da3dsoul** [comment]
Yeah, opis says there are a total of 700000 Specters. My RAM is at a steady 1300MB. I'm guessing Opis isn't reading it right or something. I'll mute Minecraft and watch a few eps of Infinite Ryvius and we shall see.

**Comment by planetguy32** [comment]
One theory is that Opis doesn't have hooks in the right place to detect when we remove tile entities - SneakyWorldUtil is supposed to be sneaky, after all.

Another theory is that we don't properly remove non-ticking tile entities. Do you have something that adds non-ticking TEs to wgen? GregTech, maybe?

**Comment by da3dsoul** [comment]
Non-ticking, huh? Hmmm.

**Comment by da3dsoul** [comment]
FMP!

**Comment by da3dsoul** [comment]
There's one.

**Comment by da3dsoul** [comment]
Unless they manage to do all that shit with metadata...

**Comment by planetguy32** [comment]
On further investigation, it looks like the code that puts TEs into the tile entity log is skipped if the TE doesn't tick - non-ticking TileEntities live only in the chunk, and we already remove the chunk.

**Comment by da3dsoul** [comment]
Okay, upon even further investigation, all of ours tick. They just don't do anything on tick. They don't override canUpdate() to return false.

**Comment by da3dsoul** [comment]
Well, I moved it over 100m, and my RAM is at 1500MB, and that is due to generating new land.

**Comment by da3dsoul** [comment]
Safe to say it is 100% fixed, and opis needs a higher perception level.
