### ISSUE TITLE
Frame movement breaks Carpenter's slopes

### ISSUE THREAD

**Issue by zetaPRIME** [planetguy32/RemainInMotion#132]
In the newest release, carpenter's slopes revert to their default state after being moved. Did not happen in 2.4.0.

**Comment by da3dsoul** [comment]
vs which release? 2.5.2? 2.5.3?

**Comment by da3dsoul** [comment]
We're probably getting ready for a new release with loads of bug fixes and mod interaction. If it has something special, we can just make a special case for it.

**Comment by zetaPRIME** [comment]
Found in 2.5.3; have not tested 2.5.2

**Comment by da3dsoul** [comment]
Ok, good enough. I can run a comparison and see what changed in the code.

**Comment by da3dsoul** [comment]
My guess is the call to onBlockAdded(). I'll write a special case for it.

**Comment by da3dsoul** [comment]
Yep.

public void onBlockAdded(World world, int x, int y, int z) {
        world.setTileEntity(x, y, z, this.createNewTileEntity(world, 0));
        this.updateLightValue(world, x, y, z);
    }

That'll do it.

**Comment by da3dsoul** [comment]
fixed in https://github.com/planetguy32/RemainInMotion/commit/b1b35c731d2a15d7b059839545ebeb1731a6e3f7
