### ISSUE TITLE
Update legacy RiM page with legacy download

### ISSUE THREAD

**Issue by Elsys656** [planetguy32/RemainInMotion#135]
Could you update the RiM page on minecraft.net with links to the legacy 1.64 download as well I had to dig around to find it as I updated my Tekkit pack with CC 1.63 and all new dependencies for such then had to track this version down to fix my machines. Not trying to be an ass with the request for the above but I'm not sure I could update my minecraft to 1.7.10 due to some other mods.

**Comment by planetguy32** [comment]
They should still be in the Mediafire folder - sorry if it's a bit hard to find. I'll put in more prominent links to them.

**Comment by planetguy32** [comment]
There's a note in the download section directing you to the Mediafire folder for 1.6.4-compatible versions.
