### ISSUE TITLE
Multipart not found

### ISSUE THREAD

**Issue by MrBretze** [planetguy32/RemainInMotion#136]
http://pastebin.com/23BFMPRq juste load and unload a chunk (frame move to 5sec)

**Comment by da3dsoul** [comment]
See #129

**Comment by da3dsoul** [comment]
Thought we fixed it. Apparently not.

**Comment by da3dsoul** [comment]
Closed cause we already have this one. Reopened the other one until it is figured out.

**Comment by planetguy32** [comment]
We've fixed this one. Expect a new build with the fix later this week.
