### ISSUE TITLE
Crash in the last forge

### ISSUE THREAD

**Issue by MrBretze** [planetguy32/RemainInMotion#140]
log: https://gist.github.com/MrBretze/f34ccb5fa20c304d15c9

**Comment by planetguy32** [comment]
@da3dsoul the access transformer should have made that public - we seem to need to do more to make it work.

**Comment by da3dsoul** [comment]
-face palm- Did you rename the archive to .jar? FMLAT doesn't work with zip.

**Comment by planetguy32** [comment]
Sorry about that, Github wouldn't accept it as a jar so I published the release on Github as a zip. It's renamed now so you can get the new one, or you can change it back to a jar.
