### ISSUE TITLE
NPE on game initializing.

### ISSUE THREAD

**Issue by anishin** [planetguy32/RemainInMotion#142]
Hello.
With version 2.6.1 of RemainInMotion I get NPE on game initialize and crash.
Crash log: http://pastebin.com/FMsdGsEZ

Maybe, you should check, is Qmunity installed or not?

Like so:

	public static void init() {

    		if(Loader.isModLoaded("qmunitylib")){
		qlInteraction.run();
    		}
	}

P. S. Sorry for my English, I'm from Russia.

**Comment by da3dsoul** [comment]
Planetguy made an oopsies.

**Comment by planetguy32** [comment]
Fixed in v2.6.1.1.
