### ISSUE TITLE
When teleporting from end to overworld chunks fail to load

### ISSUE THREAD

**Issue by lukecfairchild** [planetguy32/RemainInMotion#150]
When you use a tranlocator inbetween the end and overworld, going to the overworld from the end will fail to load chunks and even teleporting to other locations in the world still fails to load chunks. The only fix i have found is relogging. Going to the end from the overworld is fine though.

**Comment by da3dsoul** [comment]
Likely due to the process of endgame usually showing the credits screen. Worth looking into.

**Comment by da3dsoul** [comment]
OK, I need to go to work, and I'll probably forget this. Look at Entity.java->travelToDimension(int), EntityPlayerMP overrides it and if traveling from the end, it destroys the player but does not respawn it. This handling was to avoid the player getting killed while reading the credits (story). In GuiWinGame, on exit of the credits screen, it simply performs a respawn of the player. We could do it this way as well and just teleport away after respawn, but a more direct method is desirable, as weird rendering, chunkloading, and lag induced weirdness is likely to happen with that method.

**Comment by da3dsoul** [comment]
PS. That comment is for whomever decides to fix it. If I find the time, it's for me, if PlanetGuy does, for him, etc.
