### ISSUE TITLE
New NBT Packets need a larger max value than 1000

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#151]
Thank you very much, but I started working on this mod because I move mountains!

**Comment by planetguy32** [comment]
IMO most client->server packets should be size-limited for security, and we can carve out exemptions if we want to implement something like terrain uploading.

**Comment by da3dsoul** [comment]
I say this because the first time I booted after update to test teleportation from the end, one of my test setups I keep running crashed the game. It was 2 bytes too big....

**Comment by da3dsoul** [comment]
I suppose that reasoning makes sense, but as of now, I think the only client to server packets sent are handled by mc (right-click actions) or gui related things. Can you think of any others? Those are difficult to cause mischief with.

**Comment by planetguy32** [comment]
We should be at least as safe as vanilla is with respect to NBT tags causing mischief, since we only actually read one. That's good enough for me.
