### ISSUE TITLE
Refactor the nbt writeClient server common etc to be less repetitive

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#152]
For size and readability, it's always peeved me.

**Comment by planetguy32** [comment]
The idea of it is so that you can choose which NBT data gets synchronized where - writeCommonRecord gets saved on the server and synced to the client, writeClientRecord gets synced to the client, and writeServerRecord gets stored server-side.

**Comment by da3dsoul** [comment]
Yeah, I was mistaken, this was already done.
