### ISSUE TITLE
Server-side startup crash

### ISSUE THREAD

**Issue by doushio9967** [planetguy32/RemainInMotion#153]
http://pastebin.com/yrdCQYPp

RIM 2.7.0/PlanetguyLib 1.6

**Comment by planetguy32** [comment]
Try v2.7.0.1 and PL 1.6.0.1

**Comment by doushio9967** [comment]
http://pastebin.com/jU1vEA4F

Identical stacktrace with RIM 2.7.0.1/PL 1.6.0.1

**Comment by planetguy32** [comment]
Are you sure you updated the library with the one on Github? I can't reproduce it on my end.

**Comment by doushio9967** [comment]
md5sums
`f3ef3a9248cfc73c22fea56717b0c79a  PlanetguyLib-1.6.0.1.jar`
`d3a3607886dc8e017915c0f499b2808c  RemainInMotion-2.7.0.1.jar`
grabbed from /releases. So they should be the latest..

**Comment by planetguy32** [comment]
I've tried to set up something close to your

**Comment by planetguy32** [comment]
Yeah, looks like a classic client-side dependency leak. (That would be why I was having trouble reproducing it on singleplayer!) I'll fix it momentarily.

**Comment by planetguy32** [comment]
How about v2.7.0.2?

**Comment by doushio9967** [comment]
Yeah, starts up server-side with no problem.
Thank you.
