### ISSUE TITLE
Directional Carriage Engine doesn't work after restart.

### ISSUE THREAD

**Issue by H4mm3rb0y** [planetguy32/RemainInMotion#154]
After a restart the directional Carriage Engine doesn't move anymore. I have to place it new every time the Cauldron Server got restarted. I've testet this now for several restarts and its everytime. I don't know if this bug depends on the Mods i installed or the fact that i run a cauldron server. If you want i can give you a full list of all mods i used. The server-log is clear...no error, no warning, nothing that has to do with this bug.

Best Wishes
H4mm3rb0y

BTW: Nice Mod! We try to make a theater on our server with different stage sets.

Here are two screens... Before Restart:
![2015-06-15_13 16 00](https://cloud.githubusercontent.com/assets/12894182/8158812/cd44c5b4-1360-11e5-8c7b-4e34d90e71ec.png)

After Restart:
![2015-06-15_13 16 23](https://cloud.githubusercontent.com/assets/12894182/8158811/cd425540-1360-11e5-8013-186b0f6aab6e.png)

PS: This is an automatic door :D

**Comment by planetguy32** [comment]
Were the engines running when the server restarted?

**Comment by H4mm3rb0y** [comment]
no they are only activated with a pressure plate and a little circuit.
There is no way the engines run on restart because of that.

Am Mittwoch, 15. Juli 2015 schrieb planetguy32 :

**Comment by da3dsoul** [comment]
Any chance of logs? I'm guessing it's cauldron's fault, but idk.

**Comment by planetguy32** [comment]
I've replicated it without Cauldron.

**Comment by da3dsoul** [comment]
Mhmm they work for me.

**Comment by planetguy32** [comment]
After using them once they sometimes don't load properly. Try a few different directions maybe?

**Comment by H4mm3rb0y** [comment]
ill try saturday... im on vacation. but good that you ser ehat i mean ^^

Am Freitag, 17. Juli 2015 schrieb planetguy32 :

**Comment by H4mm3rb0y** [comment]
there are no errors in the logfile

Am Freitag, 17. Juli 2015 schrieb Tim A. :

**Comment by H4mm3rb0y** [comment]
I've tested it, sry this taked longer. The bug happens in all directions for me.

**Comment by planetguy32** [comment]
I seem to have fixed it just now.
