### ISSUE TITLE
Hollow Carriages not available

### ISSUE THREAD

**Issue by davidwlewis** [planetguy32/RemainInMotion#155]
Tested in a minimal setup with RiM, hollow carriage items aren't available. Using:

* PlanetguyLib-1.6.0.1
* RemainInMotion-2.7.0.2
* ForgeMultipart-1.7.10-1.2.0.345-universal

Some further investigation with MineTweaker shows that the recipes really aren't there, so I assume the FMP plugin isn't being loaded at all. Can anyone repro?

**Comment by da3dsoul** [comment]
FMP isn't really my thing, but I'm pretty sure you just use a saw to chop up a frame carriage

**Comment by da3dsoul** [comment]
Any news whether that was the case?

**Comment by davidwlewis** [comment]
I'm talking about the Hollow Carriage block (implemented [here](https://github.com/planetguy32/RemainInMotion/blob/dcf8d24188f5069e1d2840589af920739d3d9847/src/main/java/me/planetguy/remaininmotion/plugins/fmp/FMPCarriagePlugin.java), described [here](https://youtu.be/nKLOGk8TZeI?t=1m36s)). It's a frame carriage which supports the inclusion of other multipart blocks including pipes.

For some reason the plugin is not working correctly. I've had a glance at the source:  most of the initialization code is called from [here](https://github.com/planetguy32/RemainInMotion/blob/dcf8d24188f5069e1d2840589af920739d3d9847/src/main/java/me/planetguy/remaininmotion/plugins/RemIMPluginsCommon.java) but there's some creative error handling that could be hiding problems and it appears that FMPCarriagePlugin.postInit() never gets called.

**Comment by davidwlewis** [comment]
Thanks ;D

**Comment by planetguy32** [comment]
Released in v2.8.0.
