### ISSUE TITLE
Add "move-type" to "BlockSelectForMoveEvent"

### ISSUE THREAD

**Issue by Lordmau5** [planetguy32/RemainInMotion#159]
I'd like to allow the movement of my multiblocks, but not the rotation.
I can only really do it in the *BlockSelectForMoveEvent*, because the other events are being called *after* the blocks were moved.

*Edit*: Can't set a label apparently, but this is supposed to be an enhancement :P

**Comment by planetguy32** [comment]
Generally, my preferred strategy has been to fix things in a plugin, but if it's complicated it might be better to blacklist it. There is a blacklist IMC API, but it's not NBT-sensitive. There's also BlockSelectForRotateEvent, which is a subclass of BlockSelectForMoveEvent that only fires on rotations and offers the same options.

**Comment by Lordmau5** [comment]
Thanks for adding them.
I mainly wanted those to disable the rotation, since I couldn't properly figure out how to fix the tile not having the correct values.
I fixed that now.

Also, I didn't really think anyone would want to rotate a ... tank?
Still, thanks :)
