### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by Nentify** [planetguy32/RemainInMotion#163]
Sorry if this is documented somewhere, I couldn't find any information on it. What is the format for the blacklist, and what is the difference between soft and hard blacklists?

```
    S:blacklistHard=
    S:blacklistSoft=
```

**Comment by planetguy32** [comment]
Hard blacklist cancels the entire movement operation when a blacklisted block is found. Soft blacklist continues moving the other non-blacklisted blocks but leaves the blacklisted block in place.

Format is a comma-separated list of blockName or blockName@meta - eg. minecraft:dirt,minecraft:redstone@4. You'll need PlanetLib v1.8 or higher to use the blacklist.

**Comment by Nentify** [comment]
Thanks for the info! Did you mean 1.8? The latest release with RiM seems to be 1.7. Or is this a thing that was just fixed and will be fixed soon?

**Comment by planetguy32** [comment]
I just put it on CurseForge now. I'll update the RiM download in a sec...

**Comment by planetguy32** [comment]
RiM release updated.

**Comment by Nentify** [comment]
Thank you!

**Comment by planetguy32** [comment]
No problem. I'll leave this issue open for now as a reminder to document the config.

**Comment by planetguy32** [comment]
Wiki page created.
