### ISSUE TITLE
Screwdriver doesnt work

### ISSUE THREAD

**Issue by ddos666TB** [planetguy32/RemainInMotion#164]
v2.8.1
If screwdriver has different ID than 4096, it simply dosen't work while clicking carriges.
(I am playing SP with bunch of mods - like 90)

**Comment by da3dsoul** [comment]
Mine doesn't have an id 4096. You say you have a lot of mods. Would Project:Red be one? Try that screwdriver if so.

**Comment by ddos666TB** [comment]
yes PR included, but doesnt work too, have 2 different worlds one has ID 4096, other 6746, only screwdriver with id 4096 works

**Comment by da3dsoul** [comment]
Does it throw any errors?

**Comment by ddos666TB** [comment]
checking...

**Comment by ddos666TB** [comment]
no log errors, but found issue at least. It was caused by ProjectE. (some frames was duplicated using EMC in Tablet). Replaced with handcrafted and it worked.
