### ISSUE TITLE
Hollow Carriage crash

### ISSUE THREAD

**Issue by Nentify** [planetguy32/RemainInMotion#166]
I made 3 hollow carriages and placed them on some Forge Multiparts. I then powered a frame carriage and this crash ocurred: http://pastebin.com/6VLnV6mr

This is on a server.

Screenie:

![](http://i.nentify.me/dnKO7e20.png)

**Comment by planetguy32** [comment]
Looks like I'm compiling against an ancient build of FMP. Hopefully rebuilding against the version you're using should fix it.
