### ISSUE TITLE
Building this?

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#171]
FMP is causing build errors...

**Comment by planetguy32** [comment]
Is it? I got it to build fine...

Logs please?

**Comment by da3dsoul** [comment]
I don't know. gradle ignores the errors that idea gives me and gives me this:

C:\Users\Tom\Documents\GitHub\RemainInMotion\build\sources\java\me\planetguy\remaininmotion\drive\gui\ContainerDrive.java:8: error: ContainerDrive is not abstract and does not override abstract method canInteractWith(EntityPlayer) in Container
public class ContainerDrive extends ContainerPrefab {
       ^
C:\Users\Tom\Documents\GitHub\RemainInMotion\build\sources\java\me\planetguy\remaininmotion\drive\gui\GuiDriveCommon.java:22: error: GuiDriveCommon is not abstract and does not override abstract method drawGuiContainerBackgroundLayer(float,int,int) in GuiContainer
public class GuiDriveCommon extends GuiPrefab implements ITooltipDrawer {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

I know those are overriden in the Utils source, though, so I don't really get it.
I'm making a dev jar for utils so it has a more traditional import and handling.

**Comment by planetguy32** [comment]
I set up Utils as a sub-project and symlinked it into src/api/java.

**Comment by da3dsoul** [comment]
I tried it and it failed miserably on windows, mainly when github got involved and tried to figure out what goes where.

**Comment by da3dsoul** [comment]
Windows and directory links don't get along

**Comment by da3dsoul** [comment]
Okay, it worked properly after running a 'dev' build of utils. /closed i'll try to get the directory setup you have at some point, but for now, I've wasted several days messing it up and reverting.
