### ISSUE TITLE
RIM 2.8.4 Launch

### ISSUE THREAD

**Issue by Mattabase** [planetguy32/RemainInMotion#172]
https://goo.gl/PHezBJ

**Comment by da3dsoul** [comment]
It's a strange issue that happens with gradle occasionally. We'll need to rebuild and rerelease.

**Comment by Mattabase** [comment]
Sweet, Thanks for the swift response.

**Comment by walkerjonny** [comment]
Yup, just got the same error. 
I downloaded both the lib and the mod within the last half to one hour.
Waiting for rebuild and rerelease then.

**Comment by planetguy32** [comment]
Rebuilt it and the same thing happened. I'll try again when I'm at home, Eclipse and VNC don't play nicely.

**Comment by planetguy32** [comment]
I think I've tracked this one down. Unfortunately, it was my build script accidentally shading parts of my other mods into the mod being built, so you might have to re-download the whole set. I'll do a version bump.

**Comment by planetguy32** [comment]
Builds are now up on Github, pending approval on CurseForge.
