### ISSUE TITLE
Camouflage (Decoration) only works on the  Carriage Translocator

### ISSUE THREAD

**Issue by lehjr** [planetguy32/RemainInMotion#176]
While the item is being held, the decoration remains intact (results using Minetweaker):

Carriage Translocator with decoration:
"< JAKJ_RedstoneInMotion:tile.JAKJ_RedstoneInMotion_CarriageDrive:3 >.withTag({Label: 0, DecorationMeta: 0, DecorationId: 4}) * 1"

without:
"< JAKJ_RedstoneInMotion:tile.JAKJ_RedstoneInMotion_CarriageDrive:3 >.withTag({Tier: 0, Label: 0, Private: 0 as byte}) * 1"

Carriage Rotator with decoration
"< JAKJ_RedstoneInMotion:tile.JAKJ_RedstoneInMotion_CarriageDrive:6 >.withTag({DecorationMeta: 0, DecorationId: 4}) * 1"
without
"< JAKJ_RedstoneInMotion:tile.JAKJ_RedstoneInMotion_CarriageDrive:6 >.withTag({Tier: 0, Label: 0, Private: 0 as byte}) * 1"

Carriage Motor with decoration
"< JAKJ_RedstoneInMotion:tile.JAKJ_RedstoneInMotion_CarriageDrive:1 >.withTag({DecorationMeta: 0, DecorationId: 4}) * 1"

without:
"< JAKJ_RedstoneInMotion:tile.JAKJ_RedstoneInMotion_CarriageDrive:1 >.withTag({Tier: 0, Label: 0, Private: 0 as byte}) * 1"

However, once placed, only the Carriage Translocator's decoration actually shows up while the others lose theirs.

**Comment by planetguy32** [comment]
I'll look into it.
