### ISSUE TITLE
Cant craft carriage engine

### ISSUE THREAD

**Issue by pizzaluc** [planetguy32/RemainInMotion#178]
In the 2.8.6 version of this i cant seem to craft the carriage engine, the recipe dont even show up in the NEI.

i tested with the recipe from you forum post (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104611-remain-in-motion-continuation-of-redstone-in) in a normal crafting table.

**Comment by planetguy32** [comment]
You make carriage engines by placing a carriage motor and toggling stationary mode in the GUI.
