### ISSUE TITLE
[enhancement] computercraft don't save his status when moved

### ISSUE THREAD

**Issue by quentfr21** [planetguy32/RemainInMotion#181]
hello

if i make a little program in computer like this

drive=peripheral.wrap("right")
print("nb up")
a = read()

function up()
drive.move(1,false,false)
end

for n=1, a do
up()
end

after first move computer restart and the program stop (computer is on the carriage)

if you can make something i could be great

thanks in advance

**Comment by da3dsoul** [comment]
It's a known issue, if you use turtles, it works

**Comment by quentfr21** [comment]
ok thanks and sorry i don't see it in issues

**Comment by da3dsoul** [comment]
It's either way toward the back or not there. It's been talked about randomly on the forums over the past year, though. I don't blame you for not seeing it.

**Comment by quentfr21** [comment]
i just test with turtle and it's not working with simple or advanced turtle or computer carriage just move 1 time and reset and program stop

**Comment by da3dsoul** [comment]
There's a trick to it. I don't use computer craft or open computers, so I don't know the details. Go to the forum page and search for turtle. It should come up.

**Comment by quentfr21** [comment]
ok thanks

**Comment by planetguy32** [comment]
OpenComputers works just fine. ComputerCraft anything shuts down when you move it with frames (as it does when the chunk it's in is unloaded) so you need to make the turtle move alongside the frame ship.

**Comment by da3dsoul** [comment]
It probably wouldn't be too hard to make turtles disconnect in move and reconnect when done.

**Comment by quentfr21** [comment]
yes no toi hard :) thank again
