### ISSUE TITLE
Camouflaging issues

### ISSUE THREAD

**Issue by georgefst** [planetguy32/RemainInMotion#182]
Fairly obscure but important to my current build: trying to camouflage blocks to appear as white wool doesn't work e.g. template carriage decorated as white wool shows as yellow wool when placed, and memory carriage with white wool shows as lime green. Worked in previous version I was using (1.2.0) Strange.

P.S. haven't tested extensively but so far only found issue with white wool...

**Comment by da3dsoul** [comment]
Probably a metadata issue. I'll look at it.

**Comment by georgefst** [comment]
Cheers.

**Comment by da3dsoul** [comment]
I just reinstalled windows, so it'll be a few days before I get my workspace capable of building a working mod. The commit that references this is https://github.com/planetguy32/RemainInMotion/commit/ca21d1bc51f9d32613f6dfa05b57e3020c0934cf. @planetguy32 can you build this for testing?

**Comment by planetguy32** [comment]
Sorry it took a while, I had a bad upgrade so I'm now using my Debian partition. [Here](https://drive.google.com/file/d/0BzS1-0KTqrDyTlFzdmpsQlRDdk0/view?usp=sharing) is a build including that fix.

**Comment by da3dsoul** [comment]
Is it just bad upgrade week or something?

**Comment by georgefst** [comment]
Loving the quick response guys! Unfortunately though the fix isn't quite right: colour of the blocks now seems to correspond to the metadata for the carriage rather than the wool.
e.g. All frame carriages are white wool, all template carriages are yellow.

**Comment by da3dsoul** [comment]
I made another commit, this time skipping an entire section of code that might break some other thing I don't know about, but I'll blame Reika for it.

**Comment by da3dsoul** [comment]
With ABO I'll often have fixes for people to try in about 8 minutes.

**Comment by planetguy32** [comment]
Sorry for the delay, finals week so I was busy. [Here you go.](https://drive.google.com/file/d/0BzS1-0KTqrDyX2J1SHNSbU5NdVU/view?usp=sharing)

**Comment by da3dsoul** [comment]
People always say that and I don't get it. Finals are easy, you take a test (sure a long one) and then go home...much better than needing to attend classes that take the whole day.
