### ISSUE TITLE
Soft blacklist

### ISSUE THREAD

**Issue by georgefst** [planetguy32/RemainInMotion#183]
This might be a misunderstanding on my part, but there doesn't seem to be any discernible difference between the soft and hard blacklists, other than different error messages.

As I understand, trying to move a structure containing a soft-blacklisted block should move the rest of the structure and ignore that block. But nothing moves and I get the message: "Carriage motion obstructed by block" even when the blacklisted block isn't in the way.

**Comment by da3dsoul** [comment]
My bad, wrong issue number. That commit is for #182

**Comment by da3dsoul** [comment]
I finally got around to this. I found an error in the way it calculates whether the soft blacklisted block is an obstruction, causing it to always be one. I'll fix it here in the next few minutes.
