### ISSUE TITLE
[Question] Private WorldServer fields access?

### ISSUE THREAD

**Issue by Robotia** [planetguy32/RemainInMotion#186]
I had made heavy modifications to the WorldServer class and found null pointers for RIM's CarriagePackage on my server. To my surprise, I found that RIM was trying to access private fields inside WorldServer.

@planetguy32 @da3dsoul Why does RIM require access to private fields for the CarriagePackage?

**Comment by planetguy32** [comment]
The private access to WorldServer is to one of the tick lists (the other is public). Minecraft requires that both lists be in sync, so to modify the tick list we need to change both. We need to remove scheduled ticks from the initial position and schedule them at the final position, or else things like buttons would stay pressed forever when moved.

**Comment by Robotia** [comment]
Ok, thanks for the info! 

Looks like I'll have to revert my changes to TCPR's KCauldron. :sweat_smile:
