### ISSUE TITLE
No recipe for the Memory Carriage

### ISSUE THREAD

**Issue by anthonysan95** [planetguy32/RemainInMotion#187]
When trying to make the memory carriage i noticed it has no recipe..
Is it supposed to be like that?

**Comment by da3dsoul** [comment]
Give me a sec

**Comment by da3dsoul** [comment]
It works. I'll clean up some stuff and do a build, as @planetguy32 is on vacation, dealing with life, got a girlfriend, or some other time consuming task befell him.
