### ISSUE TITLE
Transduplicator spits items everywhere

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#26]
I posted this on the forums, but I'll post it as an issue for documentation/formality.

Transduplicators copy and drop a duplicate of every item in an inventory at both the source and destination. The final result is 4 copies of every item and a lot of lag on a large scale:
1 in inventory at source
1 in inventory at destination
1 on the ground at source
1 on the ground at destination

**Comment by da3dsoul** [comment]
I just figured out how to fix this, but I don't want to right now, so I'm leaving a note. Override the placeholders to not make specters at the source. They won't flash, but it is a creative item: the point is to copy a large area, not make pretty flashy effects.

**Comment by da3dsoul** [comment]
That didn't work. The forge restoring block states something might be helpful.

**Comment by planetguy32** [comment]
Can't reproduce with RemIM Git, closing.
