### ISSUE TITLE
Linear Motion Drives (Carriage Engine and Motor) lock movement while in motion

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#42]
I plan to fix this using piston style entity movement.

**Comment by da3dsoul** [comment]
I finally made this work, I suggest an immediate bump to 2.5.1 as this is a very annoying bug.

**Comment by planetguy32** [comment]
I seem to be consistently falling through carriages that are moving vertically. This would seriously mess up anyone who uses RemIM for eg. elevators, or likes to move their frameship vertically.

**Comment by da3dsoul** [comment]
Fixed.
