### ISSUE TITLE
Crash from null TileEntity

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#55]
http://pastebin.com/JU3LapTV at the end of motion, but where did the null TE come from?

**Comment by da3dsoul** [comment]
this looks like an oopies I had a while ago. Try it now.

**Comment by planetguy32** [comment]
Adaptor carriages are causing it in my workspace. I'll look into it.

**Comment by da3dsoul** [comment]
Ok yeah I don't know I just learned how to use those

**Comment by planetguy32** [comment]
It might have had to do with having multiple sides open to connections, but I've been unable to reproduce it with the latest changes.
