### ISSUE TITLE
Rotator carriages should pick up other carriages when moved

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#56]
Rotator carriages, unlike other types of drive, cannot be moved to some other attachment point on the carriage they operate on. They are directed, like RP2's carriages were. They would be more convenient if they added their selected blocks to the package, like adapter carriages do.

**Comment by da3dsoul** [comment]
I think this is done already.

**Comment by planetguy32** [comment]
Yes, it is.
