### ISSUE TITLE
Make a config or something to disable the engine sound

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#59]
Or just make one less annoying...

**Comment by da3dsoul** [comment]
I've started on sound effect replacement(s) for the engines. I will play with them and see what is less annoying/more realistic and tiles well.

**Comment by da3dsoul** [comment]
I've added three new sounds and a config for them. 0 is default, obviously. I spent a good portion of the day using my studies on acoustics and audiology to make those from scratch. You would think some nice sounds would be on the internet, but I couldn't find a thing, and I don't exactly have heavy machinery or rolling boulders to record with my mic....

**Comment by da3dsoul** [comment]
I've also added a looping mechanism to the way the sounds play (they are based on my sound files, which are 1 second long), if the carriage movement is set to take more than 1 second (mine are set to 3), the sound will replay every second while the carriage is moving.

**Comment by da3dsoul** [comment]
I'm pretty satisfied with the engine sounds now. I'll leave this open so you (planetguy) have a chance to input if you'd like.

**Comment by planetguy32** [comment]
I like your new sounds, thank you.
