### ISSUE TITLE
Make adapter carriages rotate/close sides similar to platform carriages

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#61]
With the way they work, they will only connect to one carriage at a time. Rather than closing all the others, it would be nicer if you right click the desired side and all others close.

**Comment by planetguy32** [comment]
Good idea, adaptor carriages can only connect to one carriage at a time.

**Comment by planetguy32** [comment]
Done. So as to not lose their configuration, adaptors in the world will not change, but adaptors will only be able to have one grabbing side.
