### ISSUE TITLE
Carriage adapters stop working after rotation

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#64]
I've already started working on it.

**Comment by planetguy32** [comment]
There's a problem with ISpecialMoveBehavior blocks not being persisted properly - the first one is fine, but the second doesn't work.

**Comment by da3dsoul** [comment]
Yeah I noticed. I'll see if I can fix it.

**Comment by da3dsoul** [comment]
Yay I fixed it.
