### ISSUE TITLE
ComputerCraft Computers not returning true or false

### ISSUE THREAD

**Issue by Udaldor** [planetguy32/RemainInMotion#70]
When using the Carriage Controller with ComputerCraft Computers to simulate a movement, neither true nor false is returned upon use. Attaching image.
![2015-01-09_22 49 41](https://cloud.githubusercontent.com/assets/8040468/5687937/1dd1031a-9852-11e4-8657-525e731513b1.png)

**Comment by planetguy32** [comment]
You now use a separate status() call, which retrieves whether the move would fail and a human-readable error string. 

The old one-call way wasn't thread-safe in cases when movement would actually happen - if the computer tries to wait for its current running Java call to exit before saving itself, when moved by RemIM, it would wait on its current running Java call finished, which is waiting on the computer to save its state, leaving the game deadlocked.

**Comment by Udaldor** [comment]
Brilliant. Thanks for the reply, not sure how I missed that in the documentation.

**Comment by planetguy32** [comment]
Sorry, we admittedly do have a documentation problem.
