### ISSUE TITLE
Add Carriage Chunk Loader

### ISSUE THREAD

**Issue by bluefi** [planetguy32/RemainInMotion#71]
Add a chunk loading block that keeps the chunks the carriage is in and the chunk its moving to loaded, even while in motion. 
Some chunkloaders dont work after being moved (immibis dimensional anchor) and some cause many other Problems and corrupt your world (chickenchunks)

**Comment by bluefi** [comment]
Accidently hit the post button. 

This block should be specifially designed for being moved. Maybe a config Option for being disabled and power usage.

**Comment by planetguy32** [comment]
This would be pretty tricky to implement. Someone said that they'd had good luck with Railcraft's chunk loader, but you'd need to either have two of them and move them one at a time, or use the minecart version.

**Comment by bluefi** [comment]
The minecart chunkloader sounds pretty good. But it would be good to have a RiM native Method of chunkloading.
I imagine a chunkloader block that has to be connected to the carriage and loads the chunks the carriage is in and the surrounding chunks (or with a GUI in which you can set a Radius). If energy mode is enabled the chunkloader drains a small amount of RF per tick to keep the chunks loaded and another bigger amount when moved. If there is not enough energy to be moved the carriage wont be able to move.

Wouldnt it be possible to have a chunkloader block which changes to a moving chunkloader block while in motion?

**Comment by da3dsoul** [comment]
I think this could be a good addition as well as a step forward for the code. Currently, there is a single type of specter for every moving block. That results in lighting glitches and all kinds of weirdness during motion. If we could use multiple types of specters and spawn them using class derivatives and reflection, we could solve a lot of annoyances. A specter with high light value (15, or rather 14 by MC math). A specter with low light (redstone torch and repeater). A specter with no light (stone and most things). A specter with a chunk loader. etc.

**Comment by da3dsoul** [comment]
Actually, just a Mod level list of all chunk loaders, the position, dimension, and range (maybe mode, circular or square, idk). We can just offset the position/dimension.

Or...we could just make it compatible with  other chunkloaders that don't rely on the block/tileentity to load...

**Comment by da3dsoul** [comment]
ChickenChunks is doable quite easily.

**Comment by da3dsoul** [comment]
ChickenChunks is a very small mod (all it does is add Chunkloaders, although they are quite expensive). It is not RiM native, but it should work just fine.

**Comment by da3dsoul** [comment]
If anyone knows other chunkloaders (except railcraft), list them, and I may add special casing for them, too.

**Comment by bluefi** [comment]
With Chickenbones i actually got some corrupted chunks when used in combination with RiM. every block in the chunk the chunkloader lost it's NBT Data

**Comment by da3dsoul** [comment]
Um is there a log or anything from when it happened? With the code that initializes the chunk loaders, it is very unlikely that the mod interaction in this caused it.
