### ISSUE TITLE
Extra Block Count

### ISSUE THREAD

**Issue by Pdan4** [planetguy32/RemainInMotion#72]
Hi, I've been trying to make a TBM for days. I tried using carriage adapters to move a templated TBM head, and it only worked sometimes. However, the problem now is that when I template the whole thing (>900 blocks according to the console), the engine counts extra blocks. (This happens with translocators, too).

With energy cell and wood:
![2015-01-14_04 52 12](https://cloud.githubusercontent.com/assets/6394609/5739115/eea7ae76-9ba9-11e4-92d5-348005eb1e27.png)

Without wood:
![2015-01-14_04 52 29](https://cloud.githubusercontent.com/assets/6394609/5739116/eea91392-9ba9-11e4-8fa4-1516a7631634.png)

Without energy cell:
![2015-01-14_04 52 49](https://cloud.githubusercontent.com/assets/6394609/5739117/eeb2907a-9ba9-11e4-8193-6718ed3f1eac.png)

I think it might be because I cardboard-boxed the template block source (Mekanism's cardboard box), and then put it down in the structure, then moved the structure. My guess is that doing this left phantom blocks or such, which are recursively counting, or something else horrible.

I would appreciate a reply, as I've been trying to build this darn thing for four days, staying up until 5 AM.

P.S. I think it would be nice if carriage adapters acted like classic Frames- they just join two or more frames together like glue; I found it very finicky to use them with Cuboid Carriages and Templates -- the template wouldn't pull the blocks in its shape when its source was moved by the Cuboid. Also, I think that one should be able to edit the template after it's been built/refresh the contents: I think that this could help with the problem.

Thanks,
Pdan

**Comment by da3dsoul** [comment]
Ah yes. I don't know if the blacklist is working or not right now. There are mods that have placeholder blocks. Railcraft has one. ABO has one (but ABO's cleans itself up properly, unlike railcraft's). RiM has one, too. I need to make a default blacklist with as many as I can find. The problem is that I don't know of many of the mods out there (like the one you just mentioned). We need to make a public list that can be added to here on github or something.

**Comment by Pdan4** [comment]
If I add a block to the blacklist, won't the frames not want to move it?

**Comment by da3dsoul** [comment]
I don't know. Maybe we should just make a "freelist" of blocks that cost nothing to move. Maybe make it so that blocks without collision (excluding liquids?) cost nothing. If mods cleaned up their placeholder blocks, then this wouldn't matter.

**Comment by Pdan4** [comment]
I agree that mods should clean up. I'm rebuilding it from scratch (used a filler, so hopefully no leftover ghost blocks), and will see if the same bug occurs. I think that multipart blocks or transparent blocks, or noncolliding (or some combination) shouldn't cost anything-- I can hit the weird limit with redstone and levers.

**Comment by Pdan4** [comment]
Alright, it seems that it's only counting modded blocks more than once (including the carriage engine).

**Comment by Pdan4** [comment]
I should also add that increasing the limit that a frame can carry didn't make a difference.

**Comment by da3dsoul** [comment]
Interesting. Maybe it's counting TileEntities as well as blocks or something? I work today, but it's all-intensive-purpose Friday for me. I'll look at the math.

**Comment by planetguy32** [comment]
The message makes it look like a hard-mode-specific block count limit. There were supposed to be different tiers of carriage with varying capacity, but it was never implemented. IIRC the limit per tier does not respect configuration - we should probably remove it, since there's already a non-hard-mode limit that's configurable.

**Comment by Pdan4** [comment]
Ah, I see. It's not tile entities, though. Blocks of glass and marble are counted twice.

**Comment by planetguy32** [comment]
I think we've mostly cleaned up the extra block counts.
