### ISSUE TITLE
Allow camouflaging carriage drives

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#73]

**Comment by da3dsoul** [comment]
Yes, but make it require 1 block of disguise material per side camoed. Otherwise it is too cheap and easy to make invisible traps.

**Comment by da3dsoul** [comment]
Looking at the code and seeing as the camouflage is done via crafting, a per side basis is too annoying.

**Comment by planetguy32** [comment]
This is pretty much done now.
