### ISSUE TITLE
Add GUI to carriage drives

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#74]
If carriage drives get camouflage and direction options, users will need a GUI to effectively adjust all settings. Also, a GUI will greatly simplify pairing translocators.

**Comment by da3dsoul** [comment]
Would be nice, but packets would need to be written and optimized. I also hate making packets and syncing them.

**Comment by da3dsoul** [comment]
I'd say we should take the 2.5.0 milestone off this. Kind of a big project when so much is ready for release.

**Comment by planetguy32** [comment]
I'd consider this a serious possibility at this point, and it would be quite nice to get rid of the clunky item held/sneaking/etc combinations for manipulating them. What would people think of a GUI scheme with the following functionality available?

All:
- Toggle continuous mode
- Toggle screwdriver-only mode (if the carriage is not in screwdriver-only mode, any right-click opens the GUI, else you can only open it by right-clicking it with a screwdriver
- Toggle connecting to carriages per side
- A text box showing the results of last operation (obstructed, no power, etc)

Translocator:
- Toggle each dye colour label
- Toggle private

Rotator, Directed:
- Change faced direction

**Comment by planetguy32** [comment]
Everything from above is now pretty much done, with the exception of showing the last error. That's a major usability upgrade over before.

**Comment by da3dsoul** [comment]
Now we just need an anchored Directed Carriage Drive and button. There are a lot of builds on youtube that rely on an anchored directed carriage, as that is what Funky Locomotion has.

**Comment by planetguy32** [comment]
Directed carriage drives can be anchored - the "anchored" button does that.

**Comment by da3dsoul** [comment]
Oh I didn't see it in the code
