### ISSUE TITLE
Should every block support computer control?

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#75]
Having a separate block for computer control feels a bit clunky, and causes problems if we want to allow computers to start rotation in any direction.

**Comment by da3dsoul** [comment]
I'd say use a placement method similar to adapter carriages. place the controller next to an engine, and the controller passes the command to the engine for whatever the arguments were.
ex. rotate (looks for a rotation carriage, else does nothing) y (axis) c (c for clockwise, cc for counterclockwise. looking in the negative of the axis, y would be down)
