### ISSUE TITLE
Support more mods' multipart systems

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#76]
AE, Buildcraft and Ender IO all have their own decorative facades, QmunityLib, Immibis Microblocks and FMP allow making slabs of blocks, and Carpenter's Blocks lets you decorate blocks with other blocks. It would be neat to be able to use facades as frames, a bit like FL but supporting more mods. 

The first step would be making a simple frame carriage with no logic necessary, so that mods will treat it as a decorative block. We might need to tell the mods that it's useable as a facade (at least for Buildcraft, probably not AE). Perhaps we'd want frame carriages to default to being simple, and switch them out for our current TESR-based versions if people decorate or adjust them.

This is a pretty ambitious thing depending on the number of mods we want to support.

**Comment by planetguy32** [comment]
To create BC facades, you'd need something like [this](https://github.com/Choonster/ChiselFacades/blob/cricket-1.7/src/main/java/com/choonster/chiselfacades/FacadeCreator.java) IMC message sender, and a hook in BC to check which facades are installed. It doesn't look like BC has any API for supporting facades, so we're waiting on it (BuildCraft/BuildCraft#2400).

**Comment by da3dsoul** [comment]
Yes, it will also decrease the overhead of loading a TESR for every frame.

**Comment by planetguy32** [comment]
The refactoring necessary has been done for a while, so we can fairly easily extend support to other mods if people want them. Let's close it for now.
