### ISSUE TITLE
Carriages with no decoration have invalid textures when a side is closed.

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#82]

**Comment by da3dsoul** [comment]
Trying to figure this out...

**Comment by da3dsoul** [comment]
Ok, I downloaded the source from before I went to work on this, and it is broken from 'something' you did. Just not sure what, because the logs don't mention any FileNotFoundException's.

**Comment by planetguy32** [comment]
How is it broken, not compiling? No textures showing up? Merge conflicts? The last big thing I did was I moved the non-default textures out of the assets folder.

**Comment by planetguy32** [comment]
I'd guess that it's because I'm in the middle of a refactor to let you camouflage carriage drives, and the texture mechanism for closed sides isn't hooked up yet.

**Comment by da3dsoul** [comment]
Hmmm...well I'm working on getting it to at least show me closed icons on carriages.

**Comment by da3dsoul** [comment]
I don't know I give up for now
