### ISSUE TITLE
Standing on a Rotator when it fires results in a bad The Wizard of Oz joke.

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#87]

**Comment by planetguy32** [comment]
I'm having trouble getting rotators to actually try to move me. I got them to do it once, but that wasn't near (0,0,0) to keep the problem manageable, and since then rotators have generally not been solid for me. Do you have a screenshot of a setup that causes it?

**Comment by da3dsoul** [comment]
Yeah hang on, I'll reproduce it.

**Comment by da3dsoul** [comment]
1st pic:
[spoiler][IMG]http://i60.tinypic.com/mwabro.png[/IMG][/spoiler]
Take note of the coords.
2nd pic after activating the rotator while standing on it:
[spoiler][IMG]http://i61.tinypic.com/21a0dk.png[/IMG][/spoiler]
And now I'm somewhere over the rainbow....

**Comment by da3dsoul** [comment]
PS. I know you're jealous of my world generator.

**Comment by da3dsoul** [comment]
Commented out for now to prevent scenerios like mine in survival worlds.

**Comment by da3dsoul** [comment]
This has been commented out for a while. Just use #78 as it is the root issue.
