### ISSUE TITLE
Rewrite all possible code to not use reflection

### ISSUE THREAD

**Issue by da3dsoul** [planetguy32/RemainInMotion#93]
Because it uses too much power.

**Comment by da3dsoul** [comment]
Just about finished with buildcraft. I write Additional-Buildcraft-Objects, so I figured I'd start with it.

**Comment by da3dsoul** [comment]
![BuildcraftLoop!](http://i62.tinypic.com/29glft3.png)
Woohoo!
Now to make quarries work...

**Comment by planetguy32** [comment]
Quarries and mining wells might need to be broken at their original positions and placed at their new positions.

**Comment by da3dsoul** [comment]
Mining wells do not. Quarries do. That is what I'm fixing.

**Comment by da3dsoul** [comment]
Set it up to work with teleporting nicely, too.

**Comment by da3dsoul** [comment]
Okay, now to make sure I didn't accidentally make buildcraft a dependency....

**Comment by da3dsoul** [comment]
Woo. All good. Quarries are still broken, they start destroying themselves, so I commented out. Moving BC pipes works way better now though.

**Comment by da3dsoul** [comment]
Yay quarries work now. Unreflectified Multipart. Cleaned up a lot of unnecessary reiterating and organized doRelease() a bit better. All that's left is to make an ASM Transformer for the TickNextTickList out of sync issue, and to make the ChunkWatcher thing not call in the iterator.

**Comment by da3dsoul** [comment]
It works way faster now, and Ima take a break.

**Comment by da3dsoul** [comment]
Changed the name, everywhere I look there's weird reflection, is this a funhouse? I don't need to take 5 minutes to walk 40 feet.

**Comment by da3dsoul** [comment]
Yay!
