### ISSUE TITLE
FMP ticks are not copied over

### ISSUE THREAD

**Issue by planetguy32** [planetguy32/RemainInMotion#94]
TODO check FMP integration module

Relevant FMP class: https://github.com/Chicken-Bones/ForgeMultipart/blob/master/src/codechicken/multipart/TickScheduler.scala

**Comment by da3dsoul** [comment]
Hmmm okay, I think I can fix it, we'll see. Scala has a similar layout to python (I hate python, too). That class is fairly straight forward, though.

**Comment by planetguy32** [comment]
I think you're able to get a reference to the TickScheduler with https://github.com/Chicken-Bones/CodeChickenLib/blob/1.7/src/codechicken/lib/world/WorldExtensionManager.java

I was going to work on this myself, but I opened up the place where the reflective mechanism is called and realized that I have no idea what the method does. I don't see a mechanism anywhere for copying over ticks, so I think we'll have to add a new one. I can take a crack at it if you'd rather do something else.

**Comment by da3dsoul** [comment]
Ah, okay.
